name: Deploy to ECR

on:
 
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ECR_REPOSITORY: nhkv2
  EKS_CLUSTER_NAME: nhk-test-cluster
  AWS_REGION: ap-southeast-1 
  DEPLOYMENT_NAME: purchase-ui-deployment-uat-v2
  CONTAINER_NAME: purchase-ui-v2
  NAMESPACE: uat
jobs:
  
  build:
    name: Build and Deployment
    runs-on: ubuntu-latest
    steps:
    - name: Set short git commit SHA
      id: commit
      uses: prompt/actions-commit-hash@v2

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::891377305152:role/arm-admin-github
        aws-region: ${{env.AWS_REGION}}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    
    - name: Set image tag
      run: echo "IMAGE_TAG=${GITHUB_SHA::7}" >> $GITHUB_ENV

    - name: Build Docker image and push to ECR
      if : true 
      id: build-image-and-push
      run: |
        IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:$IMAGE_TAG
        docker build -t $IMAGE_URI .
        docker push $IMAGE_URI
    
    - name: Update kube config
      id: update-kubeconfig
      run: |
        aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME }} --region ${{ env.AWS_REGION }}
        aws eks describe-cluster --name $EKS_CLUSTER_NAME --region $AWS_REGION
        aws s3 ls
    
    - name: Update EKS deployment
      run: |
        kubectl config set-context --current --namespace=${{ env.NAMESPACE }}
        kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} ${{ env.CONTAINER_NAME }}=${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ steps.commit.outputs.short }} 
        kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }}
        kubectl get pods -l app=${{ env.DEPLOYMENT_NAME }} -o jsonpath='{.items[*].metadata.name}'